version: '3.8'
services:
  db:
    image: mysql:latest
    restart: 'no'
    environment:
      MYSQL_DATABASE: 'bbdd_test'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3304:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: